import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbars from "./Pages/Navbars";
import FooterNav from "./Pages/FooterNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbars />
        {children}
        <FooterNav />
        </body>
    </html>
  );
}
