import { Inter } from "next/font/google";
import "./globals.css";
import FooterNav from "./Pages/FooterNav";
import Navbars from "./Pages/Navbars";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digital Creative Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbars />
        {children}
        <FooterNav />
        </body>
    </html>
  );
}
